export const INITIAL_WORKERS = [
  {
    id: "W-101",
    name: "Rajesh Kumar",
    category: "Skilled Worker",
    skills: ["Electrician", "Wiring", "AC Repair"],
    experience: "5 Years",
    experience_years: 5,
    location: "Madhapur, Hyderabad",
    distance_km: 1.2,
    daily_wage: 950,
    availability: "Immediate",
    trust_score: 92,
    badge: "Top Rated Pro",
    verified: true,
    rating: 4.9,
    completed_jobs: 48,
    cancellation_rate: 1.2,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-01-10", completed: true },
      { title: "Identity & DeepFace Verified", date: "2024-01-11", completed: true },
      { title: "Completed 1st Job", date: "2024-01-15", completed: true },
      { title: "Earned Top Rated Pro Badge", date: "2024-04-01", completed: true }
    ]
  },
  {
    id: "W-102",
    name: "Srinivas Rao",
    category: "Manual Worker",
    skills: ["Waiter", "Event Staff", "Catering Helper"],
    experience: "3 Years",
    experience_years: 3,
    location: "Madhapur, Hyderabad",
    distance_km: 0.8,
    daily_wage: 850,
    availability: "Immediate",
    trust_score: 88,
    badge: "Verified Pro",
    verified: true,
    rating: 4.8,
    completed_jobs: 34,
    cancellation_rate: 2.0,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-02-01", completed: true },
      { title: "Identity & DeepFace Verified", date: "2024-02-02", completed: true },
      { title: "Completed 1st Job", date: "2024-02-05", completed: true }
    ]
  },
  {
    id: "W-103",
    name: "Anitha Reddy",
    category: "Professional",
    skills: ["Data Entry", "Front Desk", "Office Assistant"],
    experience: "4 Years",
    experience_years: 4,
    location: "Hitech City, Hyderabad",
    distance_km: 2.5,
    daily_wage: 1200,
    availability: "Today",
    trust_score: 95,
    badge: "Elite Verified",
    verified: true,
    rating: 5.0,
    completed_jobs: 62,
    cancellation_rate: 0.0,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2023-11-05", completed: true },
      { title: "Identity & DeepFace Verified", date: "2023-11-06", completed: true },
      { title: "Completed 1st Job", date: "2023-11-10", completed: true }
    ]
  },
  {
    id: "W-104",
    name: "Venkatesh V.",
    category: "Skilled Worker",
    skills: ["Plumber", "Pipe Fitting", "Sanitation"],
    experience: "6 Years",
    experience_years: 6,
    location: "Gachibowli, Hyderabad",
    distance_km: 3.1,
    daily_wage: 1000,
    availability: "Immediate",
    trust_score: 90,
    badge: "Top Rated Pro",
    verified: true,
    rating: 4.85,
    completed_jobs: 52,
    cancellation_rate: 1.5,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-01-02", completed: true },
      { title: "Identity & DeepFace Verified", date: "2024-01-03", completed: true }
    ]
  },
  {
    id: "W-105",
    name: "Mohammad Rizwan",
    category: "Manual Worker",
    skills: ["Waiter", "Table Service", "Dishwasher"],
    experience: "2 Years",
    experience_years: 2,
    location: "Jubilee Hills, Hyderabad",
    distance_km: 1.9,
    daily_wage: 900,
    availability: "Immediate",
    trust_score: 86,
    badge: "Verified Pro",
    verified: true,
    rating: 4.7,
    completed_jobs: 29,
    cancellation_rate: 2.5,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-03-01", completed: true },
      { title: "Identity Verified", date: "2024-03-02", completed: true }
    ]
  },
  {
    id: "W-106",
    name: "Priya Sharma",
    category: "Professional",
    skills: ["Event Host", "Guest Management", "Bilingual Host"],
    experience: "3 Years",
    experience_years: 3,
    location: "Banjara Hills, Hyderabad",
    distance_km: 4.0,
    daily_wage: 1500,
    availability: "Tomorrow",
    trust_score: 94,
    badge: "Elite Verified",
    verified: true,
    rating: 4.95,
    completed_jobs: 41,
    cancellation_rate: 0.5,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-02-12", completed: true },
      { title: "Verified", date: "2024-02-13", completed: true }
    ]
  },
  {
    id: "W-107",
    name: "Karthik Naidu",
    category: "Skilled Worker",
    skills: ["Carpenter", "Furniture Assembly", "Interior Fitting"],
    experience: "7 Years",
    experience_years: 7,
    location: "Kondapur, Hyderabad",
    distance_km: 3.8,
    daily_wage: 1100,
    availability: "Immediate",
    trust_score: 91,
    badge: "Top Rated Pro",
    verified: true,
    rating: 4.8,
    completed_jobs: 59,
    cancellation_rate: 1.0,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2023-12-01", completed: true }
    ]
  },
  {
    id: "W-108",
    name: "Mahesh Babu",
    category: "Manual Worker",
    skills: ["Mason", "Construction Helper", "Tile Fixing"],
    experience: "4 Years",
    experience_years: 4,
    location: "Kukatpally, Hyderabad",
    distance_km: 5.2,
    daily_wage: 850,
    availability: "Immediate",
    trust_score: 83,
    badge: "Verified",
    verified: true,
    rating: 4.6,
    completed_jobs: 22,
    cancellation_rate: 3.0,
    late_arrivals: 2,
    photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-03-10", completed: true }
    ]
  },
  {
    id: "W-109",
    name: "Sunita Devi",
    category: "Skilled Worker",
    skills: ["Housekeeper", "Sanitization", "Kitchen Helper"],
    experience: "5 Years",
    experience_years: 5,
    location: "Madhapur, Hyderabad",
    distance_km: 1.5,
    daily_wage: 750,
    availability: "Immediate",
    trust_score: 89,
    badge: "Verified Pro",
    verified: true,
    rating: 4.75,
    completed_jobs: 37,
    cancellation_rate: 1.0,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-01-20", completed: true }
    ]
  },
  {
    id: "W-110",
    name: "Deepak Verma",
    category: "Skilled Worker",
    skills: ["Driver", "Valet Parking", "Commercial Driving"],
    experience: "8 Years",
    experience_years: 8,
    location: "Begumpet, Hyderabad",
    distance_km: 6.1,
    daily_wage: 1000,
    availability: "Immediate",
    trust_score: 93,
    badge: "Top Rated Pro",
    verified: true,
    rating: 4.9,
    completed_jobs: 74,
    cancellation_rate: 0.8,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2023-10-15", completed: true }
    ]
  },
  {
    id: "W-111",
    name: "Kavitha Chander",
    category: "Professional",
    skills: ["Chef", "South Indian Cuisine", "Bulk Catering"],
    experience: "6 Years",
    experience_years: 6,
    location: "Gachibowli, Hyderabad",
    distance_km: 2.8,
    daily_wage: 1600,
    availability: "Immediate",
    trust_score: 96,
    badge: "Master Chef",
    verified: true,
    rating: 4.98,
    completed_jobs: 83,
    cancellation_rate: 0.0,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2023-09-01", completed: true }
    ]
  },
  {
    id: "W-112",
    name: "Arjun Swamy",
    category: "Skilled Worker",
    skills: ["Welder", "Metal Fabrication", "Gate Repair"],
    experience: "4 Years",
    experience_years: 4,
    location: "Secunderabad, Hyderabad",
    distance_km: 7.5,
    daily_wage: 1050,
    availability: "Tomorrow",
    trust_score: 87,
    badge: "Verified Pro",
    verified: true,
    rating: 4.7,
    completed_jobs: 31,
    cancellation_rate: 2.0,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-02-18", completed: true }
    ]
  },
  {
    id: "W-113",
    name: "Narendra Prasad",
    category: "Manual Worker",
    skills: ["Painter", "Wall Coating", "Waterproofing"],
    experience: "5 Years",
    experience_years: 5,
    location: "LB Nagar, Hyderabad",
    distance_km: 8.2,
    daily_wage: 900,
    availability: "Immediate",
    trust_score: 85,
    badge: "Verified",
    verified: true,
    rating: 4.65,
    completed_jobs: 28,
    cancellation_rate: 2.2,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-03-05", completed: true }
    ]
  },
  {
    id: "W-114",
    name: "Lakshmi Prasanna",
    category: "Professional",
    skills: ["Event Supervisor", "Crowd Control", "VIP Usher"],
    experience: "4 Years",
    experience_years: 4,
    location: "Madhapur, Hyderabad",
    distance_km: 0.9,
    daily_wage: 1400,
    availability: "Immediate",
    trust_score: 93,
    badge: "Elite Verified",
    verified: true,
    rating: 4.9,
    completed_jobs: 45,
    cancellation_rate: 0.0,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-01-05", completed: true }
    ]
  },
  {
    id: "W-115",
    name: "Ramu Goud",
    category: "Manual Worker",
    skills: ["Gardener", "Lawn Mowing", "Tree Trimming"],
    experience: "6 Years",
    experience_years: 6,
    location: "Jubilee Hills, Hyderabad",
    distance_km: 2.1,
    daily_wage: 800,
    availability: "Immediate",
    trust_score: 88,
    badge: "Verified Pro",
    verified: true,
    rating: 4.8,
    completed_jobs: 39,
    cancellation_rate: 1.5,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-01-25", completed: true }
    ]
  },
  {
    id: "W-116",
    name: "Sandeep Yadav",
    category: "Skilled Worker",
    skills: ["Delivery Executive", "Package Transport", "Bike Courier"],
    experience: "2 Years",
    experience_years: 2,
    location: "Hitech City, Hyderabad",
    distance_km: 1.7,
    daily_wage: 850,
    availability: "Immediate",
    trust_score: 84,
    badge: "Fast Responder",
    verified: true,
    rating: 4.7,
    completed_jobs: 60,
    cancellation_rate: 3.0,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-02-28", completed: true }
    ]
  },
  {
    id: "W-117",
    name: "Manohar Rao",
    category: "Skilled Worker",
    skills: ["Security Guard", "Night Shift", "Access Control"],
    experience: "5 Years",
    experience_years: 5,
    location: "Financial District, Hyderabad",
    distance_km: 4.5,
    daily_wage: 950,
    availability: "Immediate",
    trust_score: 91,
    badge: "Top Security",
    verified: true,
    rating: 4.85,
    completed_jobs: 50,
    cancellation_rate: 0.5,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2023-11-20", completed: true }
    ]
  },
  {
    id: "W-118",
    name: "Kalyan Ram",
    category: "Manual Worker",
    skills: ["Warehouse Helper", "Loading & Unloading", "Packing"],
    experience: "3 Years",
    experience_years: 3,
    location: "Kondapur, Hyderabad",
    distance_km: 3.2,
    daily_wage: 800,
    availability: "Immediate",
    trust_score: 82,
    badge: "Verified",
    verified: true,
    rating: 4.6,
    completed_jobs: 25,
    cancellation_rate: 2.8,
    late_arrivals: 2,
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-03-12", completed: true }
    ]
  },
  {
    id: "W-119",
    name: "Bhavana Sen",
    category: "Professional",
    skills: ["Graphic Designer", "Banner Design", "Event Branding"],
    experience: "4 Years",
    experience_years: 4,
    location: "Madhapur, Hyderabad",
    distance_km: 1.1,
    daily_wage: 1800,
    availability: "Tomorrow",
    trust_score: 97,
    badge: "Creative Specialist",
    verified: true,
    rating: 4.99,
    completed_jobs: 70,
    cancellation_rate: 0.0,
    late_arrivals: 0,
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2023-08-10", completed: true }
    ]
  },
  {
    id: "W-120",
    name: "Vikram Singh",
    category: "Skilled Worker",
    skills: ["CCTV Technician", "Camera Setup", "Networking"],
    experience: "4 Years",
    experience_years: 4,
    location: "Gachibowli, Hyderabad",
    distance_km: 3.0,
    daily_wage: 1100,
    availability: "Immediate",
    trust_score: 89,
    badge: "Verified Pro",
    verified: true,
    rating: 4.8,
    completed_jobs: 36,
    cancellation_rate: 1.2,
    late_arrivals: 1,
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    timeline: [
      { title: "Registered", date: "2024-02-05", completed: true }
    ]
  }
];

export const INITIAL_JOBS = [
  {
    id: "J-501",
    title: "Event Waiters for Wedding Banquet",
    category: "Manual Worker",
    workers_needed: 2,
    location: "Madhapur, Hyderabad",
    salary: 900,
    duration: "8 AM - 5 PM",
    urgency: "High",
    description: "Need two waiters tomorrow from 8 AM to 5 PM near Madhapur. ₹900 each for banquet setup and table service.",
    employer_name: "Royal Banquet Hall",
    status: "Active",
    created_at: "2026-07-25 09:30 AM"
  },
  {
    id: "J-502",
    title: "Commercial Office Wiring & Light Fitting",
    category: "Skilled Worker",
    workers_needed: 1,
    location: "Hitech City, Hyderabad",
    salary: 1200,
    duration: "1 Full Day",
    urgency: "Medium",
    description: "Looking for a certified electrician to fix office wiring and LED panel lights in Hitech City Cyber Towers.",
    employer_name: "Nexus Tech Workspace",
    status: "Active",
    created_at: "2026-07-25 10:15 AM"
  },
  {
    id: "J-503",
    title: "Catering Assistants for Corporate Luncheon",
    category: "Manual Worker",
    workers_needed: 4,
    location: "Gachibowli, Hyderabad",
    salary: 950,
    duration: "10 AM - 4 PM",
    urgency: "Immediate",
    description: "Urgent requirement for 4 catering helpers at Financial District Gachibowli for corporate lunch service.",
    employer_name: "FeastCraft Catering",
    status: "Active",
    created_at: "2026-07-25 11:00 AM"
  }
];
